### ISSUE TITLE
Serializing the whole User object to the token

### ISSUE THREAD

**Issue by alexknix** [Robbert1/boot-stateless-auth#3]
Hi,

First of all, thank you very much for this awesome tutorial ! 

I have one question - I noticed that you are storing the whole User object to the token and then parse this token from the client request directly to Authentication object without any validations(is it safe?):

com.jdriven.stateless.security.TokenAuthenticationService

``` java
public Authentication getAuthentication(HttpServletRequest request) {
        final String token = request.getHeader(AUTH_HEADER_NAME);
        if (token != null) {
            final User user = tokenHandler.parseUserFromToken(token);
            if (user != null) {
                return new UserAuthentication(user);
            }
        }
        return null;
    }
```

In my case the token is a quite big right now. Is it a good idea to store the the whole User object state to the token ?

**Comment by robbertvanwaveren** [comment]
This repo is part of a blog post I made where I explain a bit more about its use-case and being safe or not. You might want to check it out.
http://blog.jdriven.com/2014/10/stateless-spring-security-part-2-stateless-authentication/

The short answer would be, yes it is safe to trust the data (as it is verified by cryptographic signing first) but you ARE exposing it to the client so you should never put in sensitive details like passwords.
